export const images = [
    {dossier: "alphabet-scrable", longueur: 26, type: "png", detail: "images/alphabet-scrabble/memory_detail_scrabble.png"},
    {dossier: "animaux", longueur: 28, type: "webp", detail: "images/animaux/memory_detail_animaux.png"},
    {dossier: "animauxAnimes", longueur: 8, type: "webp", detail: "images/animauxAnimes/memory_detail_animaux_animes.png"},
    {dossier: "animauxDomestiques", longueur: 10, type: "jpg", detail: "images/animauxDomestiques/memory_detail_animaux_domestiques.png"},
    {dossier: "chiens", longueur: 23, type: "webp", detail: "images/chiens/memory_details_chiens.png"},
    {dossier: "dinosaures", longueur: 10, type: "jpg", detail: "images/dinosaures/memory_detail_dinosaures.png"},
    {dossier: "dinosauresAvecNom", longueur: 10, type: "jpg", detail: "images/dinosauresAvecNom/memory_details_dinosaures_avec_nom.png"},
    {dossier: "legumes", longueur: 6, type: "svg", detail: "images/legumes/memory_detail.png"},
    ]

export const db = { "alphabet-scrabble" : [
    {"src": "1.png"},
    {"src": "2.png"},
    {"src": "3.png"},
    {"src": "4.png"},
    {"src": "5.png"},
    {"src": "6.png"},
    {"src": "7.png"},
    {"src": "8.png"},
    {"src": "9.png"},
    {"src": "10.png"},
    {"src": "11.png"},
    {"src": "12.png"},
    {"src": "13.png"},
    {"src": "14.png"},
    {"src": "15.png"},
    {"src": "16.png"},
    {"src": "17.png"},
    {"src": "18.png"},
    {"src": "19.png"},
    {"src": "20.png"},
    {"src": "21.png"},
    {"src": "22.png"},
    {"src": "23.png"},
    {"src": "24.png"},
    {"src": "25.png"},
    {"src": "26.png"}
],
"animaux" : [
    {"src": "1.webp"},
    {"src": "2.webp"},
    {"src": "3.webp"},
    {"src": "4.webp"},
    {"src": "5.webp"},
    {"src": "6.webp"},
    {"src": "7.webp"},
    {"src": "8.webp"},
    {"src": "9.webp"},
    {"src": "10.webp"},
    {"src": "11.webp"},
    {"src": "12.webp"},
    {"src": "13.webp"},
    {"src": "14.webp"},
    {"src": "15.webp"},
    {"src": "16.webp"},
    {"src": "17.webp"},
    {"src": "18.webp"},
    {"src": "19.webp"},
    {"src": "20.webp"},
    {"src": "21.webp"},
    {"src": "22.webp"},
    {"src": "23.webp"},
    {"src": "24.webp"},
    {"src": "25.webp"},
    {"src": "26.webp"},
    {"src": "27.webp"},
    {"src": "28.webp"}
], 
"animauxAnimes" : [
    {"src": "1.webp"},
    {"src": "2.webp"},
    {"src": "3.webp"},
    {"src": "4.webp"},
    {"src": "5.webp"},
    {"src": "6.webp"},
    {"src": "7.webp"},
    {"src": "8.webp"}
], 
"animauxDomestiques" :[
    {"src": "1.jpg"},
    {"src": "2.jpg"},
    {"src": "3.jpg"},
    {"src": "4.jpg"},
    {"src": "5.jpg"},
    {"src": "6.jpg"},
    {"src": "7.jpg"},
    {"src": "8.jpg"},
    {"src": "9.jpg"},
    {"src": "10.jpg"}
],
"chiens" : [
    {"src": "1.webp"},
    {"src": "2.webp"},
    {"src": "3.webp"},
    {"src": "4.webp"},
    {"src": "5.webp"},
    {"src": "6.webp"},
    {"src": "7.webp"},
    {"src": "8.webp"},
    {"src": "9.webp"},
    {"src": "10.webp"},
    {"src": "11.webp"},
    {"src": "12.webp"},
    {"src": "13.webp"},
    {"src": "14.webp"},
    {"src": "15.webp"},
    {"src": "16.webp"},
    {"src": "17.webp"},
    {"src": "18.webp"},
    {"src": "19.webp"},
    {"src": "20.webp"},
    {"src": "21.webp"},
    {"src": "22.webp"},
    {"src": "23.webp"}
],
"dinosaures" :[
    {"src": "1.jpg"},
    {"src": "2.jpg"},
    {"src": "3.jpg"},
    {"src": "4.jpg"},
    {"src": "5.jpg"},
    {"src": "6.jpg"},
    {"src": "7.jpg"},
    {"src": "8.jpg"},
    {"src": "9.jpg"},
    {"src": "10.jpg"}
],
"dinosauresAvecNom" : [
    {"src": "1.jpg"},
    {"src": "2.jpg"},
    {"src": "3.jpg"},
    {"src": "4.jpg"},
    {"src": "5.jpg"},
    {"src": "6.jpg"},
    {"src": "7.jpg"},
    {"src": "8.jpg"},
    {"src": "9.jpg"},
    {"src": "10.jpg"}
],
"legumes" : [
    {"src": "1.svg"},
    {"src": "2.svg"},
    {"src": "3.svg"},
    {"src": "4.svg"},
    {"src": "5.svg"}
]}